src/Entity/Activite.php
<?php

namespace App\Entity;

use App\Repository\ActiviteRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ActiviteRepository::class)
 */
class Activite
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_creation;

    /**
     * @ORM\ManyToMany(targetEntity=Contenu::class, inversedBy="activites")
     * @Assert\Count(min=1, minMessage="Pas assez de contenu dans votre acitvité", max=5, maxMessage="Trop de contenu dans votre activité")
     */
    private $contenu;

    /**
     * @ORM\ManyToMany(targetEntity=Eleve::class, inversedBy="activites")
     */
    private $eleves;


    public function __construct()
    {
        $this->contenu = new ArrayCollection();
        $this->eleves = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): self
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    /**
     * @return Collection|Contenu[]
     */
    public function getContenu(): Collection
    {
        return $this->contenu;
    }

    public function addContenu(Contenu $contenu): self
    {
        if (!$this->contenu->contains($contenu)) {
            $this->contenu[] = $contenu;
        }

        return $this;
    }

    public function removeContenu(Contenu $contenu): self
    {
        $this->contenu->removeElement($contenu);

        return $this;
    }

    /**
     * @return Collection|Eleve[]
     */
    public function getEleves(): Collection
    {
        return $this->eleves;
    }

    public function addElefe(Eleve $elefe): self
    {
        if (!$this->eleves->contains($elefe)) {
            $this->eleves[] = $elefe;
        }

        return $this;
    }

    public function removeElefe(Eleve $elefe): self
    {
        $this->eleves->removeElement($elefe);

        return $this;
    }


}

src/Form/ActiviteType.php
<?php

namespace App\Form;

use App\Entity\Activite;
use App\Entity\Contenu;
use App\Entity\Eleve;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ActiviteType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('contenu', EntityType::class, [

                'class' => Contenu::class,
                'choice_label' => 'nom',
                'multiple' => true,
                'expanded' => true,
            ])
            ->add('eleves', EntityType::class, [

                'class' => Eleve::class,
                'choice_label' => 'nom',
                'multiple' => true,
                'expanded' => true,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Activite::class,
        ]);
    }
}

src/Controller/ActiviteController.php
<?php

namespace App\Controller;

use App\Entity\Activite;
use App\Form\ActiviteType;
use App\Repository\ActiviteRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/activite")
 */
class ActiviteController extends AbstractController
{
    /**
     * @Route("/", name="activite_index", methods={"GET"})
     */
    public function index(ActiviteRepository $activiteRepository): Response
    {
        return $this->render('activite/index.html.twig', [
            'activites' => $activiteRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="activite_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $activite = new Activite();
        $form = $this->createForm(ActiviteType::class, $activite);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $activite->setDateCreation(new \DateTime('now'));
            $entityManager->persist($activite);
            $entityManager->flush();

            return $this->redirectToRoute('activite_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('activite/new.html.twig', [
            'activite' => $activite,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="activite_show", methods={"GET"})
     */
    public function show(Activite $activite): Response
    {
        $listContenu = $activite->getContenu()->toArray();
        //dd($listContenu);
        return $this->render('activite/show.html.twig', [
            'activite' => $activite,
            'listContenu'=>$listContenu
        ]);
    }

    /**
     * @Route("/{id}/edit", name="activite_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Activite $activite, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ActiviteType::class, $activite);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('activite_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('activite/edit.html.twig', [
            'activite' => $activite,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="activite_delete", methods={"POST"})
     */
    public function delete(Request $request, Activite $activite, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$activite->getId(), $request->request->get('_token'))) {
            $entityManager->remove($activite);
            $entityManager->flush();
        }

        return $this->redirectToRoute('activite_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/activite/_delete_form.html.twig
<form method="post" action="{{ path('activite_delete', {'id': activite.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ activite.id) }}">
    <button class="btn">Delete</button>
</form>

templates/activite/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/activite/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Activite{% endblock %}

{% block body %}
    <h1>Edit Activite</h1>

    {{ include('activite/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('activite_index') }}">back to list</a>

    {{ include('activite/_delete_form.html.twig') }}
{% endblock %}

templates/activite/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Activite index{% endblock %}

{% block body %}
    <h1>Activite index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Date_creation</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for activite in activites %}
            <tr>
                <td>{{ activite.id }}</td>
                <td>{{ activite.nom }}</td>
                <td>{{ activite.dateCreation ? activite.dateCreation|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('activite_show', {'id': activite.id}) }}">show</a>
                    <a href="{{ path('activite_edit', {'id': activite.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('activite_new') }}">Create new</a>
{% endblock %}

templates/activite/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Activite{% endblock %}

{% block body %}
    <h1>Create new Activite</h1>

    {{ include('activite/_form.html.twig') }}

    <a href="{{ path('activite_index') }}">back to list</a>
{% endblock %}

templates/activite/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Activite{% endblock %}

{% block body %}
    <h1>Activite</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ activite.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ activite.nom }}</td>
            </tr>
            <tr>
                <th>Date_creation</th>
                <td>{{ activite.dateCreation ? activite.dateCreation|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Nombre et nom des contenus associés </th>
                <td>
                    {% for contenu in listContenu %}
                        {{ contenu.nom }},
                    {% endfor %}
                </td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('activite_index') }}">back to list</a>

    <a href="{{ path('activite_edit', {'id': activite.id}) }}">edit</a>

    {{ include('activite/_delete_form.html.twig') }}
{% endblock %}